






# import unittest
# # import sys
# # sys.path.append('E:\PythonCode\python_study_202307\exception')
# # import my_calculator

# from my_calculator import my_adder 

# # import sys
# # import os
# # print(os.getcwd())
# # print(os.path.join(os.getcwd(), 'my_calculator'))
# # sys.path.append(os.path.join(os.getcwd(), 'my_calculator'))

# from my_calculator import my_adder

# class TestMyAdder(unittest.TestCase):
#     def test_positive_with_positive(self):
#         self.assertEqual(my_adder(5, 3), 9)
#     def test_negative_with_negative(self):
#         self.assertEqual(my_adder(-5, 3), -2)